name: gaekdam-be CI (Testcontainers)

on:
  pull_request:
    branches: ["develop", "main"]

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - run: ./gradlew test --no-daemon

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test


    env:
      JWT_SECRET_B64: og9OBhk6xH4Quwa+mWk37sISpvQ2C0ONg5l6jJRCf30=
      CRYPTO_HMAC_PEPPER_B64: og9OBhk6xH4Quwa+mWk37sISpvQ2C0ONg5l6jJRCf30=
      CRYPTO_LOCAL_KEK_B64: P32UXwOxycfN2L772hcLLC+jPcaaOzAzWiL2jdjPm+o=

      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: dummy
      DB_USERNAME: dummy
      DB_PASSWORD: dummy

      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""

      MAIL_USERNAME: asdwd@asdd
      MAIL_PASSWORD: asrtwwd1234s

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Run integration tests
        run: |
          ./gradlew integrationTest --no-daemon \
            -DJWT_SECRET_B64="${JWT_SECRET_B64}" \
            -DCRYPTO_HMAC_PEPPER_B64="${CRYPTO_HMAC_PEPPER_B64}" \
            -DCRYPTO_LOCAL_KEK_B64="${CRYPTO_LOCAL_KEK_B64}" \
            -DREDIS_HOST="${REDIS_HOST}" \
            -DREDIS_PORT="${REDIS_PORT}" \
            -DREDIS_PASSWORD="${REDIS_PASSWORD}" \
            -DMAIL_USERNAME="${MAIL_USERNAME}" \
            -DMAIL_PASSWORD="${MAIL_PASSWORD}" \
            -DDB_HOST="${DB_HOST}" \
            -DDB_PORT="${DB_PORT}" \
            -DDB_NAME="${DB_NAME}" \
            -DDB_USERNAME="${DB_USERNAME}" \
            -DDB_PASSWORD="${DB_PASSWORD}" \
            -Dmanagement.health.redis.enabled=false